import pandas as pd

# Comprehensive World Series winners data (1903-2024)
# Note: No World Series in 1904 and 1994
world_series_winners = [
    {"Year": 1903, "Winner": "Boston Americans"},
    {"Year": 1905, "Winner": "New York Giants"},
    {"Year": 1906, "Winner": "Chicago White Sox"},
    {"Year": 1907, "Winner": "Chicago Cubs"},
    {"Year": 1908, "Winner": "Chicago Cubs"},
    {"Year": 1909, "Winner": "Pittsburgh Pirates"},
    {"Year": 1910, "Winner": "Philadelphia Athletics"},
    {"Year": 1911, "Winner": "Philadelphia Athletics"},
    {"Year": 1912, "Winner": "Boston Red Sox"},
    {"Year": 1913, "Winner": "Philadelphia Athletics"},
    {"Year": 1914, "Winner": "Boston Braves"},
    {"Year": 1915, "Winner": "Boston Red Sox"},
    {"Year": 1916, "Winner": "Boston Red Sox"},
    {"Year": 1917, "Winner": "Chicago White Sox"},
    {"Year": 1918, "Winner": "Boston Red Sox"},
    {"Year": 1919, "Winner": "Cincinnati Reds"},
    {"Year": 1920, "Winner": "Cleveland Indians"},
    {"Year": 1921, "Winner": "New York Giants"},
    {"Year": 1922, "Winner": "New York Giants"},
    {"Year": 1923, "Winner": "New York Yankees"},
    {"Year": 1924, "Winner": "Washington Senators"},
    {"Year": 1925, "Winner": "Pittsburgh Pirates"},
    {"Year": 1926, "Winner": "St. Louis Cardinals"},
    {"Year": 1927, "Winner": "New York Yankees"},
    {"Year": 1928, "Winner": "New York Yankees"},
    {"Year": 1929, "Winner": "Philadelphia Athletics"},
    {"Year": 1930, "Winner": "Philadelphia Athletics"},
    {"Year": 1931, "Winner": "St. Louis Cardinals"},
    {"Year": 1932, "Winner": "New York Yankees"},
    {"Year": 1933, "Winner": "New York Giants"},
    {"Year": 1934, "Winner": "St. Louis Cardinals"},
    {"Year": 1935, "Winner": "Detroit Tigers"},
    {"Year": 1936, "Winner": "New York Yankees"},
    {"Year": 1937, "Winner": "New York Yankees"},
    {"Year": 1938, "Winner": "New York Yankees"},
    {"Year": 1939, "Winner": "New York Yankees"},
    {"Year": 1940, "Winner": "Cincinnati Reds"},
    {"Year": 1941, "Winner": "New York Yankees"},
    {"Year": 1942, "Winner": "St. Louis Cardinals"},
    {"Year": 1943, "Winner": "New York Yankees"},
    {"Year": 1944, "Winner": "St. Louis Cardinals"},
    {"Year": 1945, "Winner": "Detroit Tigers"},
    {"Year": 1946, "Winner": "St. Louis Cardinals"},
    {"Year": 1947, "Winner": "New York Yankees"},
    {"Year": 1948, "Winner": "Cleveland Indians"},
    {"Year": 1949, "Winner": "New York Yankees"},
    {"Year": 1950, "Winner": "New York Yankees"},
    {"Year": 1951, "Winner": "New York Yankees"},
    {"Year": 1952, "Winner": "New York Yankees"},
    {"Year": 1953, "Winner": "New York Yankees"},
    {"Year": 1954, "Winner": "New York Giants"},
    {"Year": 1955, "Winner": "Brooklyn Dodgers"},
    {"Year": 1956, "Winner": "New York Yankees"},
    {"Year": 1957, "Winner": "Milwaukee Braves"},
    {"Year": 1958, "Winner": "New York Yankees"},
    {"Year": 1959, "Winner": "Los Angeles Dodgers"},
    {"Year": 1960, "Winner": "Pittsburgh Pirates"},
    {"Year": 1961, "Winner": "New York Yankees"},
    {"Year": 1962, "Winner": "New York Yankees"},
    {"Year": 1963, "Winner": "Los Angeles Dodgers"},
    {"Year": 1964, "Winner": "St. Louis Cardinals"},
    {"Year": 1965, "Winner": "Los Angeles Dodgers"},
    {"Year": 1966, "Winner": "Baltimore Orioles"},
    {"Year": 1967, "Winner": "St. Louis Cardinals"},
    {"Year": 1968, "Winner": "Detroit Tigers"},
    {"Year": 1969, "Winner": "New York Mets"},
    {"Year": 1970, "Winner": "Baltimore Orioles"},
    {"Year": 1971, "Winner": "Pittsburgh Pirates"},
    {"Year": 1972, "Winner": "Oakland Athletics"},
    {"Year": 1973, "Winner": "Oakland Athletics"},
    {"Year": 1974, "Winner": "Oakland Athletics"},
    {"Year": 1975, "Winner": "Cincinnati Reds"},
    {"Year": 1976, "Winner": "Cincinnati Reds"},
    {"Year": 1977, "Winner": "New York Yankees"},
    {"Year": 1978, "Winner": "New York Yankees"},
    {"Year": 1979, "Winner": "Pittsburgh Pirates"},
    {"Year": 1980, "Winner": "Philadelphia Phillies"},
    {"Year": 1981, "Winner": "Los Angeles Dodgers"},
    {"Year": 1982, "Winner": "St. Louis Cardinals"},
    {"Year": 1983, "Winner": "Baltimore Orioles"},
    {"Year": 1984, "Winner": "Detroit Tigers"},
    {"Year": 1985, "Winner": "Kansas City Royals"},
    {"Year": 1986, "Winner": "New York Mets"},
    {"Year": 1987, "Winner": "Minnesota Twins"},
    {"Year": 1988, "Winner": "Los Angeles Dodgers"},
    {"Year": 1989, "Winner": "Oakland Athletics"},
    {"Year": 1990, "Winner": "Cincinnati Reds"},
    {"Year": 1991, "Winner": "Minnesota Twins"},
    {"Year": 1992, "Winner": "Toronto Blue Jays"},
    {"Year": 1993, "Winner": "Toronto Blue Jays"},
    # No World Series in 1994 due to strike
    {"Year": 1995, "Winner": "Atlanta Braves"},
    {"Year": 1996, "Winner": "New York Yankees"},
    {"Year": 1997, "Winner": "Florida Marlins"},
    {"Year": 1998, "Winner": "New York Yankees"},
    {"Year": 1999, "Winner": "New York Yankees"},
    {"Year": 2000, "Winner": "New York Yankees"},
    {"Year": 2001, "Winner": "Arizona Diamondbacks"},
    {"Year": 2002, "Winner": "Anaheim Angels"},
    {"Year": 2003, "Winner": "Florida Marlins"},
    {"Year": 2004, "Winner": "Boston Red Sox"},
    {"Year": 2005, "Winner": "Chicago White Sox"},
    {"Year": 2006, "Winner": "St. Louis Cardinals"},
    {"Year": 2007, "Winner": "Boston Red Sox"},
    {"Year": 2008, "Winner": "Philadelphia Phillies"},
    {"Year": 2009, "Winner": "New York Yankees"},
    {"Year": 2010, "Winner": "San Francisco Giants"},
    {"Year": 2011, "Winner": "St. Louis Cardinals"},
    {"Year": 2012, "Winner": "San Francisco Giants"},
    {"Year": 2013, "Winner": "Boston Red Sox"},
    {"Year": 2014, "Winner": "San Francisco Giants"},
    {"Year": 2015, "Winner": "Kansas City Royals"},
    {"Year": 2016, "Winner": "Chicago Cubs"},
    {"Year": 2017, "Winner": "Houston Astros"},
    {"Year": 2018, "Winner": "Boston Red Sox"},
    {"Year": 2019, "Winner": "Washington Nationals"},
    {"Year": 2020, "Winner": "Los Angeles Dodgers"},
    {"Year": 2021, "Winner": "Atlanta Braves"},
    {"Year": 2022, "Winner": "Houston Astros"},
    {"Year": 2023, "Winner": "Texas Rangers"},
    {"Year": 2024, "Winner": "Los Angeles Dodgers"},
]

# Create DataFrame
df = pd.DataFrame(world_series_winners)

# Save to CSV
df.to_csv('world_series_winners.csv', index=False)
print(f"Created dataset with {len(df)} World Series winners (1903-2024)")
print(f"Saved to world_series_winners.csv")
print(f"\nFirst few entries:")
print(df.head(10))
print(f"\nLast few entries:")
print(df.tail(10))
